### ISSUE TITLE
ETFs

### ISSUE THREAD

**Issue by knickr** [Mael-J/mstarpy#1]
Great work here and I really want to use this but I need to access the same Morningstar fund detail data for ETFs? Seems like the api request url needs to change slightly from /funds to /ETFs so probably not a large change to the code.  Also ETFs dont seem to have a specific country code. so perhaps a new ETF function.  I can pull some basic ETF data like closePrice,  name and identifiers OK but other data scrapes throws an error.

**Comment by Mael-J** [comment]
Hello,

I had a look how the etf API works and I unfortunately can get data. The API for ETF uses the SecurityId while the the API for fund uses the SecId. And I don't have any mean to get the SecurityId. If you find a way to get the security then, it will be possible to get etf data

**Comment by knickr** [comment]
From what I could tell the Security ID is the same as the fundShareClassId which you can get with  .dataPoint("fundShareClassId")

**Comment by Mael-J** [comment]
Thank you for finding the fundShareClassId. 

I changed the class Funds and the property self.code is now based on the fundShareClassId. The Funds class can detect if the asset is a fund or an etf and requests the right API. As you said ETF only work if the country parameter is set to empty string "".

By the way, how did you find that the right field was fundShareClassId ?

**Comment by knickr** [comment]
That's great.  I'Il test it this week.  

In terms of working out that fundShareClassId was the identifier needed, I looked at the api call for a particular ETF (e.g Vanguard Australian Shares ETF in Australia which has a ticker VAS) which showed what code Morningstar was using as the security identifier (https://www.us-api.morningstar.com/sal/sal-service/fund/securityMetaData/F000002TI7) i.e. F000002TI7 and then I looked at the api request when I did a search for VAS on the website which generated this request https://graphapi.prd.morningstar.com.au/graphql?query=query%20getSearchResults(%24q%3A%20String!)%20%7B%0A%20searchSecurities(term%3A%20%24q)%20%7B%0A%20total%0A%20page%0A%20pageSize%0A%20securities%20%7B%0A%20performanceId%0A%20fundShareClassId%0A%20name%3A%20standardName%0A%20securityType%0A%20exchangeId%0A%20exchangeCode%0A%20symbol%0A%20secId%0A%20apir%0A%20ticker%3A%20symbol%0A%20__typename%0A%20%7D%0A%20__typename%0A%20%7D%0A%20searchDocuments(terms%3A%20%24q)%20%7B%0A%20total%0A%20page%0A%20pageSize%0A%20documents%20%7B%0A%20id%0A%20title%0A%20description%0A%20imageUrl%0A%20status%0A%20templateName%0A%20createdDate%0A%20lastUpdatedDate%3A%20publishedDate%0A%20primaryAuthor%20%7B%0A%20name%0A%20__typename%0A%20%7D%0A%20contentTypeName%0A%20__typename%0A%20%7D%0A%20__typename%0A%20%7D%0A%7D%0A&operationName=getSearchResults&variables=%7B%22q%22%3A%22**VAS**%22%7D

and looking at the results showed that the code for the correct VAS ETF (i.e F000002TI7)  related to this field "fundShareClassId":"F000002TI7".  et voilà!

**Comment by Mael-J** [comment]
Hello,

Have you tested ?

Let me know if I can close this issue.

Thank you.

**Comment by knickr** [comment]
Sorry for the late reply.  I tested the ETFs changes you made and they work
well.  Thanks very much.  You can close this issue, although I do have a
couple of questions.

1.  Is there a list of the .GetFundsData() fields or parameters?  I found a
couple such as "quote"and "price" but wondered what else we could get.
2.  I may be missing something obvious but how can you print or show a list
of more than one fund if you do a search? In your example funds =
Funds("disruptive
technology", country="fr") print(funds.name) returns just the first fund in
the list and the same if you add the pageSize and itemRange parameters.

**Comment by Mael-J** [comment]
The GetFundsData() method is a generic function used by other methods to call the MorningStar API. In the last version 1.0.0, the GetFundsData() method in the class Funds has been removed. The new generic function to call the API is GetData() in the Parent class Security. You can access all the data with other methods such as  holdings(), riskReturnSummary() and so on.


Indeed, the class Funds() loads only one fund and is the class to access all the methods to get data about funds. 

If you want to show a list of funds you should use the method search_funds and to find fields, you can use the method search_field.

`
import mstarpy as ms

#show the name and 12 months return of 10 funds with the name disruptive technology in France.
ms.search_funds("disruptive technology",["Name", "GBRReturnM12"], country="fr", pageSize = 10)

#show all the fields for the method search_funds()
ms.search_field()

`

**Comment by knickr** [comment]
Thanks for the quick response - my error. I forgot about the search_funds
function as described in the Readme.

I am based in Australia and I have noticed that the fields for showing
historical returns such as GBRReturnM12 and ReturnM12 don't work for 'au'
funds, probably because the local Australian site (e.g.
https://www.morningstar.com.au/investments/security/fund/9144/performance) has
a different template for performance. I had a quick look and it pulls in
fields like columnDefs and netReturn to display 1,3,6,12 month historical
returns but I cannot access these fields even after changing the SITE
definitions to point au funds to https://www.morningstar.com.au in the
utils.py file.  Any suggestions?

**Comment by knickr** [comment]
Thanks.  That works for getting performance data for "au" individual
funds.

I just worked out that if I add "_ME" to the end of the historical return I
want e.g. "ReturnM12_ME" that works for searching for "au" funds with a
particular return.

**Comment by Mael-J** [comment]
Thank you for finding this solution for au funds. 

I will close this issue as everything seems sorted.

Have a nice day.
