### ISSUE TITLE
ConnectionError: Error 401

### ISSUE THREAD

**Issue by Kushagrawala** [Mael-J/mstarpy#12]
We need to fetch the latest nav for different funds for which we are making the call `fund = Funds(term=isin, country="in")` but after few requests it is giving the error below - 

```
Traceback (most recent call last):
  not_200_response
    raise ConnectionError(
ConnectionError: Error 401
            for the api https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query=F00000VF9G:nav,totalReturn&frequency=d&startDate=2023-11-20&endDate=2024-11-19&trackMarketData=3.6.3&instid=DOTCOM. Message : Unauthorized.
```

**Comment by Mael-J** [comment]
Hello,

How many funds are you trying to download ? 

It might come from morningstar.com which detects automated requests and blocks your IP temporarly.

**Comment by kushagra-saffron** [comment]
We want to fetch data for around 100 funds. How do we get around the temporary block on IP ?

**Comment by Mael-J** [comment]
Unfortunately, this is out of the scope of the package mstarpy. We built this package to access the public morningstar data. It is under the control of morningstar.com to allow the traffic.

Thank you

**Comment by Mael-J** [comment]
I will close this issue as it is out of the scope of the package.

I hope you will find  a way to solve your problem.


Thank you.
