### ISSUE TITLE
fund.nav

### ISSUE THREAD

**Issue by MestralInv** [Mael-J/mstarpy#13]
I'm having issues trying to retrieve NAV data from funds. Weeks ago, it worked perfectly and now I am having this error: "ConnectionError: Error 401
            for the api https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries?query=F00000ZTIG:nav,totalReturn&frequency=m&startDate=2014-12-13&endDate=2014-12-13&trackMarketData=3.6.3&instid=DOTCOM. Message : Unauthorized."

**Comment by Mael-J** [comment]
Hello,

I tested the following code and I could get nav history.

```
import mstarpy
import datetime

end_date = datetime.datetime.today()

start_date = end_date - datetime.timedelta(100)

fund = mstarpy.Funds('F00000ZTIG')

fund.nav(start_date, end_date)
```

In your link you try to get data in 2024, but the inception is June 2018, 2017 as written here.
https://www.acatis.de/en/investmentfunds/international-equities/acatisaiglobalequities


`
