### ISSUE TITLE
Summary Info for a Stock

### ISSUE THREAD

**Issue by kostja1979** [Mael-J/mstarpy#7]
Hi,
thanks for the great job.
Is it possible for a stock to get the info available in the "Summary" sheet? 
For instance: current value, market cap, company profile, etc...

**Comment by Mael-J** [comment]
Hello,

In the last github commit, I add the method trading tradingInformation for the class Stock. 

It gives you the the Trading information of the page Summary.

I cannot find the api which gives the Key Statistics, Company Profile.

It could be possible to get the data by scraping the page with Beautifulsoup by example. The risk is that the code would not work if the structure of the page change.

Thank you.

**Comment by kostja1979** [comment]
Thank you very much, I will try tradingInformation as it will be in the pip release!
