### ISSUE TITLE
German Exchange

### ISSUE THREAD

**Issue by kostja1979** [Mael-J/mstarpy#8]
Hi, 
the EXCHANGE list of utils.py does not include the German Exchange (Frankfurt Stock Exchange).

Thanks a lot!

**Comment by knickr** [comment]
Doesn't have the Australian Stock Exchange either (XASX).  Here is a list of all the exchanges with their 'micCode' and 'name'

XASE | American Stock Exchange
XCNQ | CNSX (Canada National Stock Exchange)
XOSE | Osaka
XTKS | Tokyo Stock Exchange
XHKF | Hong Kong Stock Exchange / Hong Kong Futures Exchange / Hang Seng Indices
XSHG | Shanghai Stock Exchange
XSHE | Shenzhen Stock Exchange
OTCM | OTC Markets (was Pinksheets)
XNSE | India National Stock Exchange
XBOM | Mumbai Stock Exchange
XKOS | Korea Stock Exchange (KOSCOM)
XNYS | New York Stock Exchange
XSES | Singapore Stock Exchange
ARCX | NYSE Arca (Pacific Stock Exchange)
XTAI | Taiwan Stock Exchange
BATS | BATS Exchange inc
XASX | Australia Stock Exchange
XNAS | NASDAQ national market
XNZE | New Zealand Stock Exchange
XLON | LSE (SEAQ national)
XOTC | OTCBB, over the counter bulletin board equities
MSCO | MSCI (EOD Only)
MicCodeTemp | Morningstar Indexes
IXUS | NASDAQ Indices
IXUS | Dow Jones Indices
XPAR | NYSE Euronext Paris Equities
IXUS | Standard + Poor’s Indices
XICE | Stockholm (Equities) Also Iceland – differentiated by field S676
XHEL | Helsinki (Equities)
XSWX | Swiss Funds
MSTARFund | Morningstar Fund
XSWX | SIX Feed (was SWX)
MABX | Madrid stock exchange Equities
XFRA | Frankfurter Börse (or Germany in general)
XEUR | EUREX (was DTB Deutsche Termin Börse)
XAMS | NYSE Euronext Amsterdam Equities
XBRU | NYSE Euronext Brussels Equities
XAMS | NYSE Euronext Indices
XETR | XETRA Frankfurt
XMUN | Munchen
XSTU | Stuttgart
XBER | Berlin
XDUS | Düsseldorf
XHAM | Hamburg
XHAN | Hannover (via CEF)
XMIL | Milan Stock Exchange (Borsa Italia)
XTSE | MDI Indices
XTSE | CBOE Indices
CHIA | Chi-X Australia
FINR | OTC Composite
USCO | US composite market
XTSE | Toronto Stock Exchange inc Ventures

**Comment by knickr** [comment]
I have been playing around with a 4 week trial premium Morningstar login
and got it from this link (which needw a Bearer Token in the header to
access) which shows the realtime exchange permissions. As I said it's not a
list of all stock exchanges eg Mexico isnt there but it is a list of the
major exchanges that provide either real time or delayed price data.

https://www.us-api.morningstar.com/QS-markets/service/queryPermission?fields=2048,8192,16384&trackMarketData=3.6.5

I also found this list also which has some other exchanges including Mexico

https://www.quantconnect.com/forum/discussion/12234/exchange-id-mapping/p1

**Comment by Mael-J** [comment]
Thank you for sharing all the exchange. It was a request by few people.
