### ISSUE TITLE
Data discrepancy

### ISSUE THREAD

**Issue by Fr4m3** [Mael-J/mstarpy#9]
Hi, I have an issue with your library. I'm running some tests on downloading data for some funds, but for a couple of equity funds, the Net Asset Value (NAV) data doesn't match with Morningstar's website.
The other one I found that's causing issues is bancoposta azionario euro
I really can't understand which data you're extracting.

This is my code

import mstarpy
import datetime
import pandas as pd
start_date = datetime.datetime(2024,2,20)
end_date = datetime.datetime(2024,2,22)
fund = mstarpy.Funds(term="bancoposta azionario internazionale", country="it")
history = fund.nav(start_date=start_date,end_date=end_date, frequency="daily")
df_history = pd.DataFrame(history)
print(fund.name)
print(df_history)

thx in advice

**Comment by knickr** [comment]
The term 'nav' is misleading - it is not the unit price history but rather the total return index (including reinvested income) used to calculate performance over different time periods. As you can see if I use your code and include both nav and totalReturn which are the same number for funds, but different for ETFs as one uses the exchange traded price and the other the underlying unit price or net asset value.

[{'nav': 10.06552, 'totalReturn': 10.06552, 'date': '2024-02-20'},
 {'nav': 10.07192, 'totalReturn': 10.07192, 'date': '2024-02-21'},
 {'nav': 10.29856, 'totalReturn': 10.29856, 'date': '2024-02-22'}]

You can get the current unit price using fund.dataPoint('ClosePrice') 

[{'ClosePrice': 11.269}]

but I don't know of a way to get a time series of historical unit prices.

**Comment by Fr4m3** [comment]
Thx Knickr, i try to find a solution after your answer but i think i need documentation of morningstar for TimeSeries function

**Comment by Mael-J** [comment]
Hello,

The function TimeSeries gets the data from the api https://www.us-api.morningstar.com/QS-markets/chartservice/v2/timeseries

On morningstar.com, the result is displayed in the chart page :

https://www.morningstar.com/funds/xnas/diisx/chart

**Comment by Fr4m3** [comment]
Thx Mael i solve it using posttax data in TimeSeries
Thx so much
